### PR TITLE
Shiva

### PR DESCRIPTION
**Pull request by Akkishiva1**
Completed the blog Seamless Authentication to Confluent Cloud Using OAuth/OIDC with Okta as Identity Provider.

### CODE REVIEW

**Comment by ashwinvenkatesan229** [comment]
@Akkishiva1 There are some conflicts with the master repo. Kindly resolve them before review

**Comment by nehruraghav** [comment]
I resolved the conflict and merged. @Akkishiva1 can you check once?

**Comment by nehruraghav** [comment]
https://platformatory.io/blog/Use-OAuth-OIDC-to-Authenticate-to-Confluent-Cloud/

**Comment by nehruraghav** [comment]
Resolved, squashed and merged:
https://platformatory.io/blog/Use-OAuth-OIDC-to-Authenticate-to-Confluent-Cloud/


Please make sure to submit 1 commit after squashing all commits. If not,
the master branch will have too many commits.

**Pull request merged**
