### PR TITLE
Subramanya - Temporal Interceptors

### PR DESCRIPTION
**Pull request by NRsubramanya**
Blog: Understanding Temporal Interceptors: Enhancing Workflow Management

### CODE REVIEW

**Review by avinash-platformatory — APPROVED** [review]
Except the Gemfile.lock changes, everything looks good

**Comment by nehruraghav** [comment]
Taking a look at this now.

**Review by nehruraghav — APPROVED** [review]
x86-linux platform exists (it just moved to a different line). As Avinash pointed out, ruby should not have been a part of the platforms.

**Comment by nehruraghav** [comment]
Merged and it looks good, but we need to remove `ruby` out of the PLATFORMS
in the Gemfile.lock.

**Pull request merged**
